services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src/backend
    environment:
      - PYTHONPATH=/src
    working_dir: /src/backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      backend-tests:
        condition: service_completed_successfully

  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src/backend
    environment:
      - PYTHONPATH=/src
    working_dir: /src/backend
    command: >
      sh -c "python -m backend.app.data.prepare_data && 
             pytest -x --durations=5 --tb=short"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend